### ISSUE TITLE
web_modules obsolete, bootstrap integration

### ISSUE THREAD

**Issue by Phoscur** [webpack/example-app#2]
Recently introducing jam to this project, web_modules folder should be obsolete.
How do you plan on using bootstrap. I guess currently it's just laying around in the jam folder...?
I'm not sure how bootstrap is expected to be used, but for now it seems as it "dissolves" into a new project (img dir), I'm not sure how it could be configured and used without changing any bootstrap files for configuration.

**Comment by Phoscur** [comment]
Mh, having a closer look, it seems you are using the mybootstrap folder as configuration..
That doesn't solve the img folder issue, but that one can (should?) be handeld seperatly.

**Comment by Phoscur** [comment]
Mh, I'd rather have a bootstrap dir, than a web_modules dir containing configuration (or at least point jam dir to web_modules)

**Comment by sokra** [comment]
:)

There is no `img` folder issue, because webpack solves it very cool ;)
Every CSS code is loaded with the [css-loader](https://github.com/webpack/css-loader) which takes care of it. (less code is loaded with the less loader and than with the css loader)

The css-loader detects `url(...)` fragments and requires the resources with a specified loader (default `file/auto`). The file-loader emits the resource as `<hash of file>.<ext>` to the output directory and returns the url.

Example:

``` less
body {
  background: url(img/background.png);
}
```

is compiled to:

``` javascript
(/*...*/)
{
  // ...
    require(/* stylesheet.less */3);
  // ...
  3: function(/*...*/) {
     module.exports = "body {\n  background: url(\""+require(/* file/auto!./img/background.png */4)+"\");\n}";
  },
  4: function(/*...*/) {
     module.exports = require.modules.c + "1234567890abcdef91857d76e89a.png";
  }
}
```

and `1234567890abcdef91857d76e89a.png` is emitted to the output directory

**Comment by sokra** [comment]
My configuration with `mybootstrap` in the `web_modules` directory is just an example. It should work with any directory.

In less code `@import` is resolved like a require if prefixed with `~`:
`@import "~abc/def";` --> like `require("abc/def")`
`@import "abc/def";` --> like `require("./abc/def")` to be compatible with existing code

my example is a bit old, it may be better not to copy variables.less, but use the exisiting one and only override some values. I'll change it in the example.

**Comment by sokra** [comment]
It may be a redundant to use `jam` and `npm` and `web_modules`, but this is for demonstration... ;)
